"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: {
//     default: "Create Next App",
//     template: "%s | Next Js",
//   },
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const isActive = pathname == "/about";
  const isActive1 =
    pathname == "/products" ||
    (pathname.startsWith("/products") && pathname != "/");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-amber-400 py-5 flex gap-4">
          <Link href={"/"}>Home</Link>
          <br />
          <Link className={isActive ? "text-green-500" : ""} href={"/about"}>
            About
          </Link>
          <br />
          <Link
            className={isActive1 ? "text-green-500" : ""}
            href={"/products"}
          >
            Products
          </Link>
          <br />
          <Link href={"/blog"}>Blog</Link>
          <br />
          <Link href={"/counter"}>Counter</Link>
          <br />
          <Link href={"/profile"}>Profile</Link>
          <br />
          <Link href={"/orders"}>Orders Page</Link>
          <br />
          <Link href={"/dashboard"}>Dashboard</Link>
          <br />
          <Link href={"/auth"}>Auth</Link>
        </header>
        {children}
        <footer className="bg-green-400 py-5">Footer</footer>
      </body>
    </html>
  );
}
